In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('call_activity.csv')
print(df)

    State  Account length  Area code International plan Voice mail plan  \
0      WV             141        408                 No              No
1      CA              13        408                 No             Yes
2      NJ              36        408                Yes             Yes
3      NV               4        510                 No              No
4      NJ             175        510                 No             Yes
..    ...             ...        ...                ...             ...
495    KS             118        408                Yes             Yes
496    CT               6        415                 No              No
497    NY             247        510                Yes             Yes
498    FL             114        408                 No              No
499    NV             159        415                 No              No

     Number vmail messages  Total day minutes  Total day calls  \
0                       42              248.8               98
1                       25              235.2              104
2                       14              167.5               79
3                       45              161.9               85
4                       20              332.1              116
..                     ...                ...              ...
495                      2              295.0              144
496                      4              221.3               67
497                     41              102.7              145
498                     23              244.2               61
499                     11              186.8               96

     Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0               42.30              267.0               93             22.70
1               39.98              277.5              118             23.59
2               28.48               59.5              116              5.06
3               27.52              298.7              101             25.39
4               56.46               50.8               59              4.32
..                ...                ...              ...               ...
495             50.15              266.4              101             22.64
496             37.62               55.3              114              4.70
497             17.46              132.1              145             11.23
498             41.51              235.7              125             20.03
499             31.76              207.8              144             17.66

     Total night minutes  Total night calls  Total night charge  \
0                  324.4                133               14.60
1                  282.5                 99               12.71
2                  244.0                 65               10.98
3                  349.8                112               15.74
4                  148.3                 66                6.67
..                   ...                ...                 ...
495                271.7                131               12.23
496                231.3                106               10.41
497                210.6                 53                9.48
498                261.8                103               11.78
499                209.5                133                9.43

     Total intl minutes  Total intl calls  Total intl charge
0                   2.8                 2               0.76
1                  13.4                 5               3.62
2                  15.2                 8               4.10
3                  17.5                13               4.73
4                   2.2                 2               0.59
..                  ...               ...                ...
495                 4.3                12               1.16
496                18.8                14               5.08
497                 1.4                11               0.38
498                16.0                12               4.32
499                 2.2                 8               0.59

[500 rows x 18 columns]

In [9]:
type(df)

pandas.DataFrame

In [5]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge
0,WV,141,408,No,No,42,248.8,98,42.30,267.0,93,22.70,324.4,133,14.60,2.8,2,0.76
1,CA,13,408,No,Yes,25,235.2,104,39.98,277.5,118,23.59,282.5,99,12.71,13.4,5,3.62
2,NJ,36,408,Yes,Yes,14,167.5,79,28.48,59.5,116,5.06,244.0,65,10.98,15.2,8,4.10
3,NV,4,510,No,No,45,161.9,85,27.52,298.7,101,25.39,349.8,112,15.74,17.5,13,4.73
4,NJ,175,510,No,Yes,20,332.1,116,56.46,50.8,59,4.32,148.3,66,6.67,2.2,2,0.59

In [6]:
df.tail()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge
495,KS,118,408,Yes,Yes,2,295.0,144,50.15,266.4,101,22.64,271.7,131,12.23,4.3,12,1.16
496,CT,6,415,No,No,4,221.3,67,37.62,55.3,114,4.70,231.3,106,10.41,18.8,14,5.08
497,NY,247,510,Yes,Yes,41,102.7,145,17.46,132.1,145,11.23,210.6,53,9.48,1.4,11,0.38
498,FL,114,408,No,No,23,244.2,61,41.51,235.7,125,20.03,261.8,103,11.78,16.0,12,4.32
499,NV,159,415,No,No,11,186.8,96,31.76,207.8,144,17.66,209.5,133,9.43,2.2,8,0.59

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  500 non-null    str
 1   Account length         500 non-null    int64
 2   Area code              500 non-null    int64
 3   International plan     500 non-null    str
 4   Voice mail plan        500 non-null    str
 5   Number vmail messages  500 non-null    int64
 6   Total day minutes      500 non-null    float64
 7   Total day calls        500 non-null    int64
 8   Total day charge       500 non-null    float64
 9   Total eve minutes      500 non-null    float64
 10  Total eve calls        500 non-null    int64
 11  Total eve charge       500 non-null    float64
 12  Total night minutes    500 non-null    float64
 13  Total night calls      500 non-null    int64
 14  Total night charge     500 non-null    float64
 15  Total intl minutes     500 non-null    float64
 16  Total intl calls       500 non-null    int64
 17  Total intl charge      500 non-null    float64
dtypes: float64(8), int64(7), str(3)
memory usage: 70.4 KB

In [8]:
df['Total intl charge']

0      0.76
1      3.62
2      4.10
3      4.73
4      0.59
       ...
495    1.16
496    5.08
497    0.38
498    4.32
499    0.59
Name: Total intl charge, Length: 500, dtype: float64

In [11]:
type(df['Total intl charge'])

pandas.Series

## Create a DataFrame from a dict

In [12]:
tempdict = {
    'Name' : ['Atanu','Lewis','Max','Landow'],
    'Degignation' : ['Viewer','Driver','Driver','Driver'],
    'Salary':[00000,100000000,10000000,10000000]
}

In [13]:
pd.DataFrame(tempdict)

     Name Degignation     Salary
0   Atanu      Viewer          0
1   Lewis      Driver  100000000
2     Max      Driver   10000000
3  Landow      Driver   10000000

In [14]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge'],
      dtype='str')

In [16]:
df.dtypes

State                        str
Account length             int64
Area code                  int64
International plan           str
Voice mail plan              str
Number vmail messages      int64
Total day minutes        float64
Total day calls            int64
Total day charge         float64
Total eve minutes        float64
Total eve calls            int64
Total eve charge         float64
Total night minutes      float64
Total night calls          int64
Total night charge       float64
Total intl minutes       float64
Total intl calls           int64
Total intl charge        float64
dtype: object

In [18]:
df.State

0      WV
1      CA
2      NJ
3      NV
4      NJ
       ..
495    KS
496    CT
497    NY
498    FL
499    NV
Name: State, Length: 500, dtype: str